"""Audit a robot's actuator configuration: inertia, gains, and sanity checks.

Re-run this whenever the model changes (new masses, new links, a different home
pose, a different control rate). Gains depend on the *compiled* model, so they go
stale silently when the model moves.

See doc/actuator_tuning.md for the method behind every number printed here.

Usage:
  python scripts/check_actuators.py                      # defaults below
  python scripts/check_actuators.py --robot tahiti_c1
"""

from __future__ import annotations

import argparse
import math
import pathlib

import mujoco
import numpy as np

# ─── Robot presets ────────────────────────────────────────────────────────────
# armature is the RotorInertia x GearRatio^2 reflected inertia (doc §3).
# Each motor entry: (name, armature, tau_peak, tau_rated, v_noload, joint matcher)

ROBOTS = {
  "tahiti_c1": dict(
    # Generated by scripts/urdf_to_mjcf.py; swap to the .urdf to audit the source.
    model="src/assets/robots/tahiti_c1/xmls/tahiti_c1.xml",
    meshes="src/assets/robots/tahiti_c1/xmls/meshes",
    pose={"hip_pitch": -0.225, "knee": 0.45, "ankle_pitch": 0.225},
    foot_body="left_ankle_roll_link",
    side_prefix=("left",),
    motors=[
      # MyActuator X12-320: 20:1, rotor 12.9 kg.cm^2
      ("X12-320", 12.9e-4 * 20.0**2, 320.0, 85.0, 13.09, lambda n: "ankle" not in n),
      # MyActuator X6-60: 19.612:1, rotor 0.66 kg.cm^2
      ("X6-60", 0.66e-4 * 19.612**2, 60.0, 20.0, 18.43, lambda n: "ankle" in n),
    ],
  ),
  "g1": dict(
    model="src/assets/robots/unitree_g1/xmls/g1.xml",
    meshes="src/assets/robots/unitree_g1/xmls/assets",
    pose={"hip_pitch": -0.1, "knee": 0.3, "ankle_pitch": -0.2},
    foot_body="left_ankle_roll_link",
    side_prefix=("left",),
    motors=[
      ("7520-22", 0.02510, 139.0, 139.0, 20.0,
       lambda n: any(k in n for k in ("hip_roll", "knee"))),
      ("7520-14", 0.01018, 88.0, 88.0, 32.0,
       lambda n: any(k in n for k in ("hip_pitch", "hip_yaw", "waist_yaw"))),
      ("2x5020", 0.00722, 50.0, 50.0, 37.0,
       lambda n: "ankle" in n or "waist" in n),
      ("4010", 0.00425, 5.0, 5.0, 22.0, lambda n: "wrist_pitch" in n or "wrist_yaw" in n),
      ("5020", 0.00361, 25.0, 25.0, 37.0, lambda n: True),  # catch-all: arms
    ],
  ),
}

# ─── Design targets (doc §5–§8) ───────────────────────────────────────────────
F_CONTROL = 50.0  # Hz = 1 / (sim.timestep * decimation)
THETA_SAT_TARGET = 1.4  # rad; want 1.0-2.0
ZETA = 1.0  # type 1.0-1.3 when I_ref includes the load
V_GAIT = 5.0  # rad/s, typical peak joint speed during gait


def equivalent_box(mass: float, ixx: float, iyy: float, izz: float) -> tuple[float, ...]:
  """Solid-box dimensions matching a COM-referenced inertia tensor.

  Useful for spotting a link whose mesh and inertial data disagree.
  """
  a, b, c = ixx * 12 / mass, iyy * 12 / mass, izz * 12 / mass
  return tuple(
    math.sqrt(max(v, 0.0)) for v in ((b + c - a) / 2, (a + c - b) / 2, (a + b - c) / 2)
  )


def body_frame_inertia(model: mujoco.MjModel, b: int) -> tuple[float, float, float]:
  """Diagonal of a body's inertia expressed in the BODY frame.

  ``model.body_inertia`` is stored in the principal frame, with ``body_iquat``
  giving the rotation. Comparing those numbers directly against mesh axes would
  hide an orientation mismatch behind an axis permutation, so rotate back first.
  """
  rot = np.zeros(9)
  mujoco.mju_quat2Mat(rot, model.body_iquat[b])
  rot = rot.reshape(3, 3)
  inertia = rot @ np.diag(model.body_inertia[b]) @ rot.T
  return float(inertia[0, 0]), float(inertia[1, 1]), float(inertia[2, 2])


def load(cfg: dict) -> tuple[mujoco.MjModel, mujoco.MjData]:
  meshdir = pathlib.Path(cfg["meshes"])
  assets = {
    p.name: p.read_bytes()
    for ext in ("*.STL", "*.stl", "*.obj", "*.OBJ")
    for p in meshdir.glob(ext)
  }
  spec = mujoco.MjSpec.from_file(cfg["model"], assets=assets)
  if not any(j.type == mujoco.mjtJoint.mjJNT_FREE for j in spec.joints):
    spec.worldbody.bodies[0].add_freejoint()
  model = spec.compile()
  data = mujoco.MjData(model)

  for j in range(model.njnt):
    name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_JOINT, j)
    if model.jnt_type[j] != mujoco.mjtJoint.mjJNT_HINGE:
      continue
    for key, val in cfg["pose"].items():
      if name.endswith(key + "_joint"):
        data.qpos[model.jnt_qposadr[j]] = val
  mujoco.mj_forward(model, data)
  return model, data


def support_torques(model, data, foot_body: str) -> np.ndarray:
  """Static joint torques with the full body weight carried by one foot."""
  bid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, foot_body)
  if bid < 0:
    return np.zeros(model.nv)
  weight = float(sum(model.body_mass)) * 9.81
  jp, jr = np.zeros((3, model.nv)), np.zeros((3, model.nv))
  mujoco.mj_jacBody(model, data, jp, jr, bid)
  return -jp.T @ np.array([0.0, 0.0, weight])


def main() -> None:
  ap = argparse.ArgumentParser()
  ap.add_argument("--robot", default="tahiti_c1", choices=sorted(ROBOTS))
  args = ap.parse_args()
  cfg = ROBOTS[args.robot]

  model, data = load(cfg)
  M = np.zeros((model.nv, model.nv))
  mujoco.mj_fullM(model, M, data.qM)
  Minv = np.linalg.inv(M)
  grav = support_torques(model, data, cfg["foot_body"])
  w_ceil = 2 * math.pi * F_CONTROL / 5

  print(f"model  : {cfg['model']}")
  print(f"mass   : {float(sum(model.body_mass)):.2f} kg")
  print(f"control: {F_CONTROL:.0f} Hz  ->  omega ceiling {w_ceil / (2 * math.pi):.1f} Hz")
  print(f"targets: theta_sat {THETA_SAT_TARGET} rad, zeta {ZETA}\n")

  hdr = ("joint", "armat", "I_load", "I_ref", "Kp", "Kd", "w[Hz]", "th_sat",
         "scale", "grav", "flags")
  print("%-24s%9s%8s%8s%8s%7s%7s%8s%7s%7s  %s" % hdr)
  print("-" * 116)

  groups: dict[str, list] = {}
  for j in range(model.njnt):
    name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_JOINT, j)
    if model.jnt_type[j] != mujoco.mjtJoint.mjJNT_HINGE:
      continue
    if not name.startswith(cfg["side_prefix"]):  # one side is representative
      continue
    motor = next((m for m in cfg["motors"] if m[5](name)), None)
    if motor is None:
      continue
    mname, armature, tau_pk, tau_rt, v_max, _ = motor

    dof = model.jnt_dofadr[j]
    i_load = 1.0 / Minv[dof, dof]  # operational-space (free) inertia, doc §4
    i_ref = armature + i_load

    kp = min(tau_pk / THETA_SAT_TARGET, i_ref * w_ceil**2)
    omega = math.sqrt(kp / i_ref)
    kd = 2 * ZETA * i_ref * omega
    theta_sat = tau_pk / kp

    lo, hi = model.jnt_range[j]
    span = (hi - lo) if model.jnt_limited[j] else 2 * math.pi
    scale = min(0.25 * tau_pk / kp, 0.4 * span)

    flags = []
    if not 500 <= tau_pk / armature <= 8000:
      flags.append(f"tau/I={tau_pk / armature:.0f}!")
    if not 0.02 <= i_load / armature <= 10:
      flags.append(f"Il/Ia={i_load / armature:.2f}!")
    if omega >= w_ceil * 0.99:
      flags.append("w-capped")
    if not 0.15 <= scale <= 0.5:
      flags.append(f"scale={scale:.3f}!")
    if kd * V_GAIT > 0.5 * tau_pk:
      flags.append("Kd-gait!")
    if kd * v_max > tau_pk:
      flags.append("Kd-vmax!")
    if abs(grav[dof]) > 0.5 * tau_rt:
      flags.append("grav!")

    print("%-24s%9.5f%8.4f%8.4f%8.1f%7.2f%7.2f%8.2f%7.3f%7.1f  %s"
          % (name, armature, i_load, i_ref, kp, kd, omega / (2 * math.pi),
             theta_sat, scale, abs(grav[dof]), " ".join(flags)))
    groups.setdefault(mname, []).append((name, i_ref, tau_pk, v_max))

  # Grouped gains: what actually goes into <robot>_constants.py.
  print("\nGrouped gains (one BuiltinPositionActuatorCfg per motor type):")
  print("%-12s%7s%10s%10s%9s%9s   %s"
        % ("motor", "n", "I_ref med", "spread", "Kp", "Kd", "checks"))
  print("-" * 88)
  for mname, entries in groups.items():
    irefs = [e[1] for e in entries]
    tau_pk, v_max = entries[0][2], entries[0][3]
    med = float(np.median(irefs))
    spread = max(irefs) / min(irefs)
    kp = min(tau_pk / THETA_SAT_TARGET, med * w_ceil**2)
    kd = 2 * ZETA * math.sqrt(kp * med)
    checks = []
    checks.append(f"Kd*v_gait={kd * V_GAIT:.0f}/{0.5 * tau_pk:.0f}"
                  + ("" if kd * V_GAIT < 0.5 * tau_pk else " FAIL"))
    checks.append(f"Kd*v_max={kd * v_max:.0f}/{tau_pk:.0f}"
                  + ("" if kd * v_max < tau_pk else " FAIL"))
    if spread > 3.0:
      checks.append(f"SPREAD {spread:.1f}x - consider splitting")
    print("%-12s%7d%10.4f%9.1fx%9.1f%9.2f   %s"
          % (mname, len(entries), med, spread, kp, kd, "  ".join(checks)))
    for name, iref, _, _ in entries:
      z_eff = kd / (2 * math.sqrt(kp * iref))
      w = math.sqrt(kp / iref) / (2 * math.pi)
      print("               %-30s w=%5.2f Hz  zeta_eff=%.2f" % (name, w, z_eff))

  # Mesh vs inertia consistency: catches links whose STL is missing geometry.
  print("\nMesh / inertia consistency (equivalent solid box vs mesh bounding box):")
  for b in range(1, model.nbody):
    bname = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, b)
    if not bname.startswith(cfg["side_prefix"]) or model.body_mass[b] < 1e-6:
      continue
    box = equivalent_box(float(model.body_mass[b]), *body_frame_inertia(model, b))
    gids = [g for g in range(model.ngeom) if model.geom_bodyid[g] == b
            and model.geom_type[g] == mujoco.mjtGeom.mjGEOM_MESH]
    if not gids:
      continue
    mid = model.geom_dataid[gids[0]]
    a, n = model.mesh_vertadr[mid], model.mesh_vertnum[mid]
    v = model.mesh_vert[a:a + n]
    mesh = v.max(0) - v.min(0)
    worst = max(abs(math.log(max(box[i], 1e-6) / max(mesh[i], 1e-6))) for i in range(3))
    tag = "  <-- MISMATCH" if worst > math.log(2.5) else ""
    print("  %-24s inertia %.3f x %.3f x %.3f   mesh %.3f x %.3f x %.3f%s"
          % (bname, *box, *mesh, tag))


if __name__ == "__main__":
  main()
